[metadata]
name = safe_input_veritas
version = 0.1.0
description = Robust and extensible user input validation framework

[flake8]
max-line-length = 88
extend-ignore = E203, W503
exclude =
    .git,
    __pycache__,
    build,
    dist,
    .venv,
    venv,
    .tox,
    env,
    *.egg-info,
    .eggs,
    .mypy_cache,
    .pytest_cache,
    tests/__pycache__

[isort]
profile = black
line_length = 88
known_first_party = safeinputveritas
skip_gitignore = true

[tool:pytest]
addopts = --maxfail=1
testpaths = tests

[coverage:run]
branch = True
source =
    src/safe_input_veritas

[coverage:report]
show_missing = True
fail_under = 95

[options]
package_dir =
    = src
packages = find:

[options.packages.find]
where = src

[options.package_data]
safe_input_veritas =
    locales/*.json
