[tox]
envlist = py, flake8, isort, black, mypy, coverage

[testenv]
setenv =
    PYTHONPATH = {toxinidir}/src
deps =
    pytest
    pytest-cov
commands =
    pytest --cov=safe_input_veritas --cov-fail-under=95 --cov-report=term-missing tests/

[testenv:flake8]
deps = flake8
commands = flake8 src tests

[flake8]
max-line-length = 88
exclude =
    .tox,
    .venv,
    venv,
    env,
    build,
    dist,
    __pycache__,
    *.egg-info,
    .eggs,
    .mypy_cache,
    .pytest_cache,
    tests/__pycache__

[testenv:isort]
deps = isort
commands = isort --check --diff src tests

[isort]
line_length=88
skip=.tox,.venv,venv,env,build,dist

[testenv:black]
deps = black
commands = black --check --diff src tests

[testenv:mypy]
deps = mypy
commands = mypy --ignore-missing-imports src tests

[testenv:coverage]
setenv =
    PYTHONPATH = {toxinidir}/src/safe_input_veritas
deps = coverage
commands =
    coverage report --fail-under=95
    coverage html
